version: '3'
name: Docker-example
services:
  db:
    image: mongo:latest
    volumes:
      - /data:/data/db 
    networks:
        - serv
    container_name: example-database
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "3000:3000"
    networks:
       - serv
    depends_on: 
      - "db"
    container_name: example-webapp
    links:
      - "db:database"
networks:
    serv:



